SwiftGen/SwiftGen

- Sources/L10n/SwiftGenL10nEnumBuilder.swift
Added "import Foundation" at top of L10N code.
Makes it more usable as build-script, since you don't need to add it manually (or y some ugly pre-pending script) each time.
> Added import Foundation at top of L10N code.

- Sources/Common/SwiftGenVersion.swift
- Sources/Common/SwiftIdentifier.swift
- Sources/L10n/SwiftGenL10nEnumBuilder.swift
Updated to Xcode 7b6, fixed join method application.
> Xcode 7b6 join Fix

- CHANGELOG.md
- README.md
- Sources/Colors/SwiftGenColorEnumBuilder.swift
- Tests/Colors/ColorsTests.swift
- Tests/Colors/expected/ListDefaults.swift.out
Fix parsing value, that starts with 0x and alpha is absent
> Fix incorrect color parsing

- Rakefile
Expand paths for binary, template, and framework.
> Fixed an issue with install paths prefixed with ~

- CHANGELOG.md
- GenumKit/Parsers/ColorsFileParser.swift
- SwiftGen.xcodeproj/project.pbxproj
- UnitTests/TestSuites/ColorsTests.swift
- UnitTests/fixtures/colors.json
- swiftgen-cli/colors.swift
- Adds the ability to parse JSON color files rather than just txt, clr, or xml.
> JSON parser for colors

- CHANGELOG.md
- SwiftGen.xcodeproj/project.pbxproj
- UnitTests/TestSuites/StoryboardTests.swift
- UnitTests/TestSuites/StringsTests.swift
- UnitTests/expected/Storyboards-Anonymous-Swift3.swift.out
- UnitTests/expected/Storyboards-Wizard-Swift3.swift.out
- UnitTests/expected/Strings-Localizable-Swift3.swift.out
- documentation/Templates.md
- templates/storyboards-swift3.stencil
- templates/strings-swift3.stencil
> Add Swift3 Templates 

- CHANGELOG.md
- GenumKit/Parsers/ColorsFileParser.swift
- README.md
- UnitTests/fixtures/colors.txt
- Fixes #140 
- Also a random README fix
> Txt comment bug

- CHANGELOG.md
- SwiftGen.xcodeproj/project.pbxproj
- UnitTests/TestSuites/StringsTests.swift
- UnitTests/expected/Strings-File-Dot-Syntax-Swift3.swift.out
- templates/strings-dot-syntax-swift3.stencil
- templates/strings-dot-syntax.stencil
> Add Swift3 support to Dot-Syntax template [fixed]

- GenumKit/Parsers/StringsFileParser.swift
- UnitTests/TestSuites/StringsTests.swift
> Requested changes for #192

- CHANGELOG.md
- GenumKit/Stencil/Filters.swift
- UnitTests/Filters/StringFiltersTests.swift
Currently written just to pass the unit-tests, this needs a thorough check of what's expected, and then fix it. For example #233.
A good idea would be to look how other languages provide such functionality, and compare our output to theirs.
> More string filter test cases

- COMMUNITY.md
Based on https://github.com/Moya/contributors
> Community guidelines

- CHANGELOG.md
- CONTRIBUTING.md
> Adding a paragraph about branch name conventions used in SwiftGen

- CHANGELOG.md
- Sources/Info.plist
- SwiftGen.podspec
> Release 5.1.1

- CHANGELOG.md
- Podfile.lock
- Pods/Manifest.lock
- Pods/SwiftGenKit/Sources/Parsers/AssetsCatalogParser.swift
- Pods/Target Support Files/SwiftGenKit/Info.plist
- Sources/Info.plist
- SwiftGen.podspec
- rakelib/changelog.rake
> Bump version to 5.2.0

- CHANGELOG.md
- README.md
- Sources/Commander/ConfigCommands.swift
- Sources/Commander/OutputDestination.swift
- Sources/Commander/ParserCLICommands.swift
- Sources/Commander/TemplatesCommands.swift
- Sources/Config/ConfigEntry.swift
- Sources/Logs.swift
- Sources/TemplateRef.swift
> Fix TemplateRef to handle empty string paths

- circle.yml
- rakelib/changelog.rake
- rakelib/utils.rake
See https://github.com/SwiftGen/templates/pull/86 — porting changes/fixes back here
> Fix CircleCI builds (for Xcode9 version search) + sync:all_files

- CONTRIBUTING.md
I've done none of the following four things, I'm just fixing a super minor typo.
---
> s/while project/whole project/

- Gemfile
- rakelib/utils.rake
[Rakefile] Fix wrong test about CIRCLECI vs CI
[Gemfile] Extract rubocop in dev group
[Gemfile] Extract octokit in development group
This commit should fix https://github.com/Homebrew/homebrew-core/pull/25405
> Fixing builds on homebrew

- CHANGELOG.md
- Sources/SwiftGenKit/Parsers/InterfaceBuilder/Platform.swift
- Sources/SwiftGenKit/Parsers/InterfaceBuilder/Storyboard.swift
- Tests/Fixtures/Resources/IB-iOS/Anonymous.storyboard
Fixes #367.
Original issue was https://github.com/SwiftGen/SwiftGenKit/issues/58.
> IB: match target runtime using prefix

- CHANGELOG.md
- Documentation/templates/xcassets/swift3.md
- Documentation/templates/xcassets/swift4.md
- Sources/SwiftGenKit/Parsers/AssetsCatalog/CatalogEntry.swift
- Sources/SwiftGenKit/Stencil/AssetsCatalogContext.swift
- Tests/Fixtures/Generated/XCAssets/swift3-context-all-customname.swift
- Tests/Fixtures/Generated/XCAssets/swift3-context-all-forceNamespaces.swift
- Tests/Fixtures/Generated/XCAssets/swift3-context-all-no-all-values.swift
- Tests/Fixtures/Generated/XCAssets/swift3-context-all-publicAccess.swift
- Tests/Fixtures/Generated/XCAssets/swift4-context-all-customname.swift
- Tests/Fixtures/Generated/XCAssets/swift4-context-all-forceNamespaces.swift
- Tests/Fixtures/Generated/XCAssets/swift4-context-all-no-all-values.swift
- Tests/Fixtures/Generated/XCAssets/swift4-context-all-publicAccess.swift
- Tests/Fixtures/Generated/XCAssets/swift4-context-all.swift
- Tests/Fixtures/StencilContexts/XCAssets/all.yaml
- Tests/Fixtures/StencilContexts/XCAssets/colors.yaml
- Tests/Fixtures/StencilContexts/XCAssets/images.yaml
- Tests/TemplatesTests/XCAssetsTests.swift
- templates/xcassets/swift3.stencil
- templates/xcassets/swift4.stencil
Resolves #453 by adding a new parameter called "forceProvidesNamespaces".
> Add parameter for xcasset namespacing configuration 

- CHANGELOG.md
- Documentation/templates/MigrationGuide.md
- Sources/SwiftGenKit/Parsers/InterfaceBuilder/Storyboard.swift
- Tests/Fixtures/StencilContexts/IB-macOS/anonymous.yaml
Refs #515 (fixes one part of it).
If the user sets a custom class for every scene, we wouldn't add the platform module to the list of modules. This PR fixes that edge case.
> IB: Fix missing module

- CHANGELOG.md
- CONTRIBUTING.md
- Dangerfile
- README.md
> Fix typos in README + Improve Dangerfile

- CHANGELOG.md
- Sources/SwiftGen/Commander/TemplatesCommands.swift
> Fix templates subcommand

- CHANGELOG.md
- Sources/SwiftGen/Commander/ConfigCommands.swift
- Sources/SwiftGen/Logs.swift
> Config: error reporting

- Package.resolved
- Podfile.lock
- Pods/Manifest.lock
- Pods/StencilSwiftKit/Sources/StencilSwiftKit/SwiftIdentifier.swift
- Pods/Target Support Files/StencilSwiftKit/Info.plist
No changelog entry as at release, we add a link to the SSK changelog, and it only contains a bugfix 🤷‍♂️
> #trivial StencilSwiftKit 2.7.1

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- Dangerfile
- rakelib/changelog.rake
- rakelib/check_changelog.rb
- rakelib/release.rake
- rakelib/utils.rake
Refs #230.
* Check that the CHANGELOG entries correctly end with `.  `
* Integrate the `changelog:check` into Danger
> Danger: changelog check

- Documentation/ConfigFile.md
_(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
---
- LINE 32: `templatePath:` -> `templateName:`
- strings: `structured-swift3` -> `structured-swift4`
- xcassets: `swift3`, `customswift3` -> `swift4`
> Fix typo + Update template version in ConfigFile.md #trivial
