SwiftGen/SwiftGen

- GenumKit/EnumBuilders/ImageEnumBuilder.swift
- GenumKit/EnumBuilders/StoryboardEnumBuilder.swift
- GenumKit/EnumBuilders/StringEnumBuilder.swift
- UnitTests/TestSuites/ImagesTests.swift
- UnitTests/TestSuites/StoryboardTests.swift
- UnitTests/TestSuites/StringsTests.swift
- UnitTests/expected/Images-Entries-ExcludeUnderscore.swift.out
- UnitTests/expected/Images-Entries-Underscore.swift.out
- UnitTests/expected/Storyboards-All-Underscores.swift.out
- UnitTests/expected/Strings-Lines-ExcludeUnderscore.swift.out
- UnitTests/expected/Strings-Lines-Underscore.swift.out
- swiftgen-cli/images.swift
- swiftgen-cli/storyboards.swift
- swiftgen-cli/strings.swift
Added excludechars argument to image, string, storyboard command
> Excludechars

- swiftgen-cli/strings.swift
The "strings" command was attempting to generate colors instead.
(I haven't tested this so I don't know if any other changes are needed.)
> Fix broken strings command

- CHANGELOG.md
- GenumKit/GenumKit.podspec
- GenumKit/Stencil/Contexts.swift
- Pods/Target Support Files/GenumKit/Info.plist
- README.md
- SwiftGen.playground/Pages/Storyboards-Demo.xcplaygroundpage/Contents.swift
- SwiftGen.playground/Pages/Storyboards-Demo.xcplaygroundpage/timeline.xctimeline
- UnitTests/expected/Storyboards-All-CustomName.swift.out
- UnitTests/expected/Storyboards-All-Defaults.swift.out
- UnitTests/expected/Storyboards-Anonymous-Defaults.swift.out
- UnitTests/expected/Storyboards-Empty.swift.out
- UnitTests/expected/Storyboards-Message-Defaults.swift.out
- UnitTests/expected/Storyboards-Message-Lowercase.swift.out
- swiftgen-cli/storyboards.swift
- templates/storyboards-default.stencil
- templates/storyboards-lowercase.stencil
Works around https://github.com/AliSoftware/SwiftGen/issues/57
I've left the default Segue and Scene names as is. We can't use StoryboardScene and StoryboardSegue as they conflict with the protocols. I'm not attached to a particular name if anyone has something better.
> Unnest Scene and Segue structs to work around a LLVM bug

- README.md
When following the README Xcode complained of the following problem:
Code:
`UIStoryboard.Scene.Login.Start` 
Error:
`Type 'UIStoryboard' has no member 'Scene'`
This is due to UIStoryboard not being extended, a solution is provided where `UIStoryboard.Scene` is replaced with `StoryboardScene`.
The same is true for `UIStoryboard.Segue` to `StoryboardSegue`
> Updated ReadME to use StoryboardScene and StoryboardSegue

- CHANGELOG.md
- UnitTests/expected/Colors-List-RawValue.swift.out
- UnitTests/expected/Images-Entries-Defaults.swift.out
- UnitTests/expected/Images-File-AllValues.swift.out
- UnitTests/expected/Images-File-CustomName.swift.out
- UnitTests/expected/Images-File-Defaults.swift.out
- UnitTests/expected/Storyboards-All-CustomName.swift.out
- UnitTests/expected/Storyboards-All-Defaults.swift.out
- UnitTests/expected/Storyboards-Anonymous-Defaults.swift.out
- UnitTests/expected/Storyboards-Empty.swift.out
- UnitTests/expected/Storyboards-Message-Defaults.swift.out
- UnitTests/expected/Storyboards-Message-Lowercase.swift.out
- UnitTests/expected/Strings-Entries-Defaults.swift.out
- UnitTests/expected/Strings-File-CustomName.swift.out
- UnitTests/expected/Strings-File-Defaults.swift.out
- UnitTests/expected/Strings-File-UTF8-Defaults.swift.out
- UnitTests/expected/Strings-Lines-Defaults.swift.out
- templates/colors-rawValue.stencil
- templates/images-allvalues.stencil
- templates/images-default.stencil
- templates/storyboards-default.stencil
- templates/storyboards-lowercase.stencil
- templates/strings-default.stencil
To use SwiftGen in tandem with [SwiftLint](https://github.com/realm/SwiftLint) the colons on `strings-default.stencil`, `storyboards-default.stencil` and `images-default.stencil` need to be updated to remove the prefixing space.
I realise this is a trivial improvement, but will reduce compiler warnings when used with SwiftLint!
Pull request recreated after Master was updated. [Old Pull Request](https://github.com/AliSoftware/SwiftGen/pull/78)
> Update colons to pass SwiftLint

- CHANGELOG.md
- GenumKit/GenumKit.podspec
- Pods/Local Podspecs/GenumKit.podspec.json
- UnitTests/expected/Storyboards-All-CustomName.swift.out
- UnitTests/expected/Storyboards-All-Defaults.swift.out
- UnitTests/expected/Storyboards-Message-Defaults.swift.out
- templates/storyboards-default.stencil
> Fixed typos: 'instanciate' -> 'instantiate'

- CHANGELOG.md
- swiftgen-cli/ArgumentsUtils.swift
- swiftgen-cli/colors.swift
- swiftgen-cli/images.swift
- swiftgen-cli/storyboards.swift
- swiftgen-cli/strings.swift
Currently, `swiftgen` will always write the generated content to the `--output` file. This also happens when the generated content is exactly equal to what is already contained in the output file. 
Xcode will pick up the "change" regardless of the content and this behaviour can lead to build loops, especially when using `IBInspectable` and `IBDesignable`.
I changed `write:` to take a second parameter `onlyIfChanged:` that controls wether the generated content will be written to a file if it is exactly the same as already in the file. I also changed commands `strings`, `storyboards`, `images` and `colors` to use the new behaviour.
This idea was also discussed in #89.
> Don't write unchanged contents to file

- SwiftGen.playground/Pages/Colors-Demo.xcplaygroundpage/Contents.swift
- SwiftGen.playground/Pages/Storyboards-Demo.xcplaygroundpage/Contents.swift
- SwiftGen.playground/Pages/Strings-Demo.xcplaygroundpage/Contents.swift
The header text was misplaced and some examples didn't work therefore.
> fix misplacement in playground files

- README.md
I really like the `init(family:size:)` convenience constructor in the [usage example](https://github.com/AliSoftware/SwiftGen#usage-1). This changes the default template to match.
> Update UIFont example on readme to match default template

- CHANGELOG.md
- UnitTests/expected/Fonts-Dir-CustomName.swift.out
- UnitTests/expected/Fonts-Dir-Default.swift.out
- templates/fonts-default.stencil
Trying out the new font type generation in SwiftGen 1.0 and hit a snag:
The one custom font I have in this app is `Apple Symbols.ttc`. Here is the generated code:
```swift
// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen
import UIKit.UIFont
protocol FontConvertible {
func font(size: CGFloat) -> UIFont!
}
extension FontConvertible where Self: RawRepresentable, Self.RawValue == String {
func font(size: CGFloat) -> UIFont! {
return UIFont(font: self, size: size)
}
}
extension UIFont {
convenience init!<FontType: FontConvertible where FontType: RawRepresentable, FontType.RawValue == String>(font: FontType, size: CGFloat) {
self.init(name: font.rawValue, size: size)
}
}
struct FontFamily {
enum AppleSymbols: String {
case Regular = "AppleSymbols"
}
}
``` …
> Add FontConvertible protocol to generated enums

- SwiftGen.playground/Resources/Wizard.storyboardc/designable.storyboard
- UnitTests/fixtures/Anonymous.storyboard
- UnitTests/fixtures/Dependency.storyboard
- UnitTests/fixtures/Message.storyboard
- UnitTests/fixtures/Placeholder.storyboard
- UnitTests/fixtures/Wizard.storyboard
It annoys me to no end that Xcode stores (seemingly unnecessary) tool and OS version information in storyboard and XIB files. I like to isolate these changes from features so that any conflicts are obvious that they come from a finicky tool instead of an feature change to the file.
While updating this metadata in the test fixtures (by simply looking at them), I noticed a bunch of generated binary files for the storyboard inside the playground are checked in. These don't appear to be necessary to be versioned as they will simply be regenerated when someone views the storyboard.
> Update IB metadata

- UnitTests/expected/Storyboards-All-CustomName.swift.out
- UnitTests/expected/Storyboards-All-Default.swift.out
- UnitTests/expected/Storyboards-Anonymous-Default.swift.out
- UnitTests/expected/Storyboards-Anonymous-Swift3.swift.out
- UnitTests/expected/Storyboards-Empty.swift.out
- UnitTests/expected/Storyboards-Message-Default.swift.out
- UnitTests/expected/Storyboards-Message-Lowercase.swift.out
- UnitTests/expected/Storyboards-Wizard-Swift3.swift.out
- templates/storyboards-default.stencil
- templates/storyboards-lowercase.stencil
- templates/storyboards-swift3.stencil
- templates/storyboards-uppercase.stencil
Adds missing return to generated `initialViewController` method in storyboard templates.
> Gotta return

- CHANGELOG.md
- UnitTests/expected/Colors-Empty.swift.out
- UnitTests/expected/Colors-File-CustomName.swift.out
- UnitTests/expected/Colors-File-Default.swift.out
- UnitTests/expected/Colors-List-Default.swift.out
- UnitTests/expected/Colors-List-RawValue.swift.out
- UnitTests/expected/Colors-Txt-File-CustomName.swift.out
- UnitTests/expected/Colors-Txt-File-Default.swift.out
- UnitTests/expected/Fonts-Dir-CustomName.swift.out
- UnitTests/expected/Fonts-Dir-Default.swift.out
- UnitTests/expected/Images-Entries-Default.swift.out
- UnitTests/expected/Images-File-AllValues.swift.out
- UnitTests/expected/Images-File-CustomName.swift.out
- UnitTests/expected/Images-File-Default.swift.out
- templates/colors-default.stencil
- templates/colors-rawValue.stencil
- templates/fonts-default.stencil
- templates/images-allvalues.stencil
- templates/images-default.stencil
Fix #143 
**Note:** as said in the other thread, I didn't test the output in a real project. Based on @Megatron1000 comments, it should work since it was working before.
OS X support didn't change localizables and storyboards templates, so if it was working before, it should still work as expected.
> Add tvOS and watchOS support for Images, Fonts, Colors

- CHANGELOG.md
- UnitTests/expected/Strings-Localizable-Swift3.swift.out
- templates/strings-swift3.stencil
`NSLocale.current()` has been renamed to `Locale.current`
> Fix swift 3 renaming compile error

- CHANGELOG.md
- SwiftGen.xcodeproj/project.pbxproj
- UnitTests/TestSuites/FontsTests.swift
- UnitTests/expected/Fonts-Dir-CustomName-Swift3.swift.out
- UnitTests/expected/Fonts-Dir-Default-Swift3.swift.out
- UnitTests/expected/Storyboards-Anonymous-Swift3.swift.out
- UnitTests/expected/Storyboards-Wizard-Swift3.swift.out
- templates/fonts-swift3.stencil
- templates/storyboards-swift3.stencil
As of Xcode 8 beta 6, we now get the following build warning for storyboards and fonts:
> 'where' clause next to generic parameters is deprecated and will be removed in the future version of Swift
Added a `swift3` template for fonts and made a change to the `swift3` template for storyboards in order to prevent this warning.
> Improvements for Swift 3 in Xcode 8 beta 6

- CHANGELOG.md
- UnitTests/expected/Storyboards-AdditionalImport-Swift3.swift.out
- UnitTests/expected/Storyboards-Anonymous-Swift3.swift.out
- UnitTests/expected/Storyboards-Wizard-Swift3.swift.out
- templates/storyboards-swift3.stencil
- Change swift 3 storyboard segue template's sender from `AnyObject` to `Any`
- Added afonsograca to changelog
> Storyboard Segue Templates

- CHANGELOG.md
Apparently we can't directly modify the changelog
> Add changelog entry for escaping reserved keywords

- CHANGELOG.md
- GenumKit/Parsers/AssetsCatalogParser.swift
- GenumKit/Parsers/ColorsFileParser.swift
- GenumKit/Parsers/FontsFileParser.swift
- GenumKit/Parsers/StoryboardParser.swift
- GenumKit/Parsers/StringsFileParser.swift
- UnitTests/TestSuites/ColorsTests.swift
- UnitTests/TestSuites/FontsTests.swift
- UnitTests/TestSuites/ImagesTests.swift
- UnitTests/TestSuites/StoryboardsTests.swift
- UnitTests/TestSuites/StringsTests.swift
- UnitTests/TestsHelper.swift
- swiftgen-cli/colors.swift
- swiftgen-cli/fonts.swift
- swiftgen-cli/images.swift
- swiftgen-cli/storyboards.swift
- swiftgen-cli/strings.swift
- swiftgen-cli/templates.swift
Just did a quick review of places where paths get passed around, and tried to ensure that actual `Path` instances get used there.
The code in FontsFileParser can be simplified further pending https://github.com/kylef/PathKit/pull/25.
Hopefully I haven't missed too many, definitely needs a second look.
> Consolidate use of PathKit

- swiftgen-cli/colors.swift
Travis didn't catch this, because it doesn't build the swiftgen target, only the unit tests.
> Fix compile error in swiftgen-cli

- CHANGELOG.md
- GenumKit/Parsers/StoryboardParser.swift
- GenumKit/Stencil/Contexts.swift
- UnitTests/TestSuites/StoryboardsTests.swift
- UnitTests/expected/Storyboards-AdditionalImport-Swift3.swift.out
- UnitTests/expected/Storyboards-All-CustomName.swift.out
- UnitTests/expected/Storyboards-All-Default.swift.out
- UnitTests/expected/Storyboards-osx-AdditionalImport-Default.swift.out
- UnitTests/expected/Storyboards-osx-AdditionalImport-Swift3.swift.out
- UnitTests/expected/Storyboards-osx-All-Default.swift.out
- UnitTests/fixtures/Storyboards-OSX/AdditionalImport-osx.storyboard
- UnitTests/fixtures/Storyboards-iOS/AdditionalImport.storyboard
- swiftgen-cli/storyboards.swift
- templates/storyboards-default.stencil
- templates/storyboards-lowercase.stencil
- templates/storyboards-osx-default.stencil
- templates/storyboards-osx-lowercase.stencil
- templates/storyboards-osx-swift3.stencil
- templates/storyboards-swift3.stencil
- templates/storyboards-uppercase.stencil
This deprecates the `--import` option.
As a bonus, this fixes an issue where a user could have a class name collision with classes from modules.
> Parse storyboard customModule property

- CHANGELOG.md
- UnitTests/expected/Strings-File-Dot-Syntax-Swift3.swift.out
- templates/strings-dot-syntax-swift3.stencil
Fixes #241, is also an example on how to get rid of the `p0`, `p1` variables.
> Strings dot-syntax-swift3 fix

- CHANGELOG.md
- Sources/ArgumentsUtils.swift
- Sources/main.swift
---
This fixes the swiftlint errors reported in #296 without addressing the CI reporting issue.
> Fix enum names to conform to Swift 3 syntax

- CHANGELOG.md
- Sources/ArgumentsUtils.swift
- Sources/colors.swift
- Sources/fonts.swift
- Sources/images.swift
- Sources/storyboards.swift
- Sources/strings.swift
- SwiftGen.xcodeproj/project.pbxproj
Fixes #244.
Doesn't actually remove the options, but throw an error instead, and showing the user what they should use instead.
> Disable old CLI options

- CHANGELOG.md
- Rakefile
---
* The scripts to automate the releases — and copy the content of the CHANGELOG entries for the latest version into the GitHub release text — currently fails because when sending the request to the GitHub API to update the release text, it seems that 🔗  and other characters were creating problems and made the API fail
* But more importantly, with this new format the links to the other CHANGELOGs will be more visible to users, inciting them to actually go and read those CHANGELOGs (the current format was probably _too_ discreet and I think a lot of people didn't read those changes in the other modules) as they are generally _more_ important than the changes done in this repo which is only the CLI part of SwiftGen
> Update CHANGELOG format for linked CHANGELOGs

- CHANGELOG.md
- README.md
---
I've seen a lot of people preferring downloading the ZIP to install SwiftGen, especially unarchiving it in their project folder and committing it to git, so that every co-worker are assured to use the same version on all their machines for this project. This also allows people to have different versions of SwiftGen for different projects, in case some projects are ready to update but not others.
That's also the installation method that is used by Sourcery, so we'd have some consistency here
> Improve Install instructions in README

- CHANGELOG.md
- Sources/ArgumentsUtils.swift
- Sources/main.swift
---
This is a proposal to implement issue #283.
It includes disabling the default value for the `templateOption` argument which will break existing usage which does not provide any template when invoking swiftgen.
> Show error when combining `-t` and `-p` cli options #283

- CHANGELOG.md
- Sources/ArgumentsUtils.swift
- Sources/colors.swift
- Sources/fonts.swift
- Sources/images.swift
- Sources/main.swift
- Sources/storyboards.swift
- Sources/strings.swift
- Sources/templates.swift
Implements the SwiftGen CLI side of https://github.com/SwiftGen/templates/issues/1.
Related PR: https://github.com/SwiftGen/templates/pull/13
I'd like some feedback on the rewritten text in the `templates` command, as well as the changelog entry with migration instructions (really barebones for now).
> Templates in subdirectories

- CHANGELOG.md
- SwiftGen.podspec
---
When installing SwiftGen via CocoaPods, the `file.zip` file downloaded by CocoaPods containing the SwiftGen release (binary + templates) before unzipping was kept after install. This is because we explicitly used `s.preserve_paths = '*'` in the `.podspec`
The solution (inspired by SwiftLint's podspec) is to explicitly exclude this `file.zip` in the files to keep in the podspec.
> Remove unneeded file.zip from CocoaPods installs

- CHANGELOG.md
- Sources/Commander/ConfigCommands.swift
- Sources/Commander/OutputDestination.swift
- Sources/Commander/ParserCLICommands.swift
- Sources/Commander/TemplatesCommands.swift
- Sources/Logs.swift
Fixes the second part of #346 (\cc @NachoSoto)
Basically, I've removed all `logMessage(.error, …)` calls and replaced intermediate `do { } catch { }` blocks with `ErrorPrettifier.execute { }`, which rethrows the error (and let it bubble up all the way to `Commander.main`) — just prettifying non-SwifGen, generic `NSCocoaErrors` thrown in that closure before rethrowing them, so that "Permission denied" errors and such are not printed in an ugly message in `stderr` but are presented in a nicer way.
@djbe this PR is meant to be merged after #347 so I've made the request to merge into your fix/templateref-empty-path branch. We can either merge #347 first then this one next, or merge this one first into #347 then merge #347 to merge it all to master.
> Errors now always throw and thus exit with non-zero exit code

- CHANGELOG.md
- Sources/main.swift
- SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
Otherwise the default behavior of commander is that when you invoke
`$ swiftgen --help`
It will print the help of `swiftgen config run --help`
> Print full help when no subcommand used but --help flag set

- CHANGELOG.md
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-multiple.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-multiple.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-multiple.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-multiple.swift
- templates/strings/flat-swift3.stencil
- templates/strings/flat-swift4.stencil
- templates/strings/structured-swift3.stencil
- templates/strings/structured-swift4.stencil
---
This closes #427
Some keys generated by SwiftGen can have more then 5 parameters, it makes SwiftLint unhappy :'(
> Disabled function_parameter_count rule SwiftLint

- README.md
Fixes #457.
Until the release of 6.0, this can be tested with:
```bash
mint install SwiftGen/SwiftGen@master --global=false
```
> Add mint installation (merge for 6.0 only)

- CHANGELOG.md
- Sources/SwiftGenKit/Parsers/Strings/PlaceholderType.swift
- Tests/SwiftGenKitTests/StringParserTests.swift
Fixes #501.
We were missing some cases such as (see docs https://en.wikipedia.org/wiki/Printf_format_string#Flags_field):
- `% d` --> pad with spaces
- `%#x` --> "alternate form" (no idea)
- `%0d` --> pad with zeroes
What's still missing:
Apparently this is possible:
```c
printf("%*d", 5, 10)
printf("%.*s", 3, "abcdef)
```
So both the width and precision fields can accept dynamic values (`int`). After some testing we've noticed that the `String(format:)` initialiser has quite a few bugs with these dynamic fields, so we're not adding them for now.
> Strings: fix format parser to handle `% d` and `%#x`

- Sources/SwiftGen/TemplateRef.swift
- Tests/SwiftGenTests/ConfigLintTests.swift
- Tests/SwiftGenTests/ConfigReadTests.swift
This is to better match our focus on configuration users, so that they don't suddenly get some weird errors about CLI flags.
The errors themselves are still usable for CLI users, because the configuration field names match the CLI options.
> Clarify template name/path errors

- CHANGELOG.md
- Scripts/SwiftLint.sh
- Scripts/swiftlint_no_disable_all.sh
Seems no one noticed that since #409, the linting of output on CI has been broken (not on device though, if you have `swiftlint` installed globally).
Also, the linting performance is abysmal, this PR improves things. It goes from `22.44s` down to `9.80s`.
> Fix (completely) broken swiftlint for output

- CHANGELOG.md
- Scripts/SwiftLint.sh
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-multiple.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-multiple.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-multiple.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-customname.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-no-comments.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-publicAccess.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-multiple.swift
- templates/strings/flat-swift3.stencil
- templates/strings/flat-swift4.stencil
- templates/strings/structured-swift3.stencil
- templates/strings/structured-swift4.stencil
Refs #501.
Adds a `tr` function that doesn't accept any parameters, and directly returns the result of `NSLocalizedString`.
> Strings: Use `tr` without params for strings without params

- README.md
This PR has two commits. First an update to what the README says on where to find the built products, which did not match what I found.
Second, some instructions on how to properly set up Ruby environment before building. I'm not sure if you want these instructions in this form, but it would have helped me though! Also, maybe there are better ways to do this that I'm missing.
> Update building instructions in README

- CHANGELOG.md
- Sources/SwiftGen/Commander/ConfigCommands.swift
- Sources/SwiftGen/Config/Config.swift
- Sources/SwiftGen/Config/ConfigEntry.swift
- Sources/SwiftGen/Config/ConfigOutput.swift
- Sources/SwiftGen/Path+AppSupport.swift
- SwiftGen.xcodeproj/project.pbxproj
- Tests/Fixtures/Configs/config-deprecated-commands.yml
- Tests/Fixtures/Configs/config-with-multi-entries.yml
- Tests/SwiftGenTests/ConfigLintTests.swift
- Tests/SwiftGenTests/ConfigReadTests.swift
Check if:
- `input_dir` & `output_dir` exist
- command is deprecated
- command `inputs` item exists
- command `outputs.output` parent exists
- command `outputs` template can be resolved
> Better config linting

- CHANGELOG.md
- README.md
- Sources/SwiftGen/Commander/ParserCLICommands.swift
- Sources/SwiftGen/Commander/TemplatesCommands.swift
- Sources/SwiftGen/Info.plist
- Sources/SwiftGen/ParserCLI.swift
- Sources/SwiftGen/TemplateRef.swift
- Sources/SwiftGenKit/Info.plist
- SwiftGen.playground/Pages/JSON-Demo.xcplaygroundpage/Contents.swift
- SwiftGen.playground/Pages/Plist-Demo.xcplaygroundpage/Contents.swift
- SwiftGen.playground/Pages/YAML-Demo.xcplaygroundpage/Contents.swift
- SwiftGen.podspec
- SwiftGenKit.podspec
- Tests/SwiftGenTests/ConfigLintTests.swift
- rakelib/changelog.rake
I've moved the "bug fixes" changelog section to be after "new features". I've adapted the rake script as well. The order is now:
- Breaking changes
- New features
- Bug fixes
- Internal changes
> Release 6.0.0

- CHANGELOG.md
- Sources/SwiftGenKit/Parsers/Strings/StringsEntry.swift
- Sources/SwiftGenKit/Stencil/StringsContext.swift
- Tests/Fixtures/Generated/Strings/flat-swift3-context-multiple.swift
- Tests/Fixtures/Generated/Strings/flat-swift4-context-multiple.swift
- Tests/Fixtures/Generated/Strings/structured-swift3-context-multiple.swift
- Tests/Fixtures/Generated/Strings/structured-swift4-context-multiple.swift
- Tests/Fixtures/Resources/Strings/LocMultiline.strings
- Tests/Fixtures/StencilContexts/Strings/multiline.yaml
- Tests/Fixtures/StencilContexts/Strings/multiple.yaml
Fixes #528.
This ensures that keys ending with a `.` don't produce a last, empty level name. It adds the `.` to the previous level. For example:
- key: `"hello.world."` --> level name: `"world."` --> swift identifier: `world`
- key: `"hello.world..."` --> level name: `"world..."` --> swift identifier: `world`
Our `swiftIdentifier:"pretty"` filter ends up stripping the `_` characters at the end, but if a user uses a custom template with `swiftIdentifier:"normal"`, they'd end up with `world_` and `world___`.
Note that https://github.com/SwiftGen/StencilSwiftKit/pull/105 fixes a crash in the filter itself when transforming empty strings.
> Strings: fix parser for key ending with `.`

- CHANGELOG.md
* well…
---
- CHANGELOG entry was pointing to PR 529 instead of 530
- Missing trailing two spaces at end of one of the entries
> Fix wrong link in CHANGELOG

- CHANGELOG.md
- Tests/Fixtures/Generated/Colors/literals-swift3-context-defaults-customname.swift
- Tests/Fixtures/Generated/Colors/literals-swift3-context-defaults-publicAccess.swift
- Tests/Fixtures/Generated/Colors/literals-swift3-context-defaults.swift
- Tests/Fixtures/Generated/Colors/literals-swift3-context-multiple.swift
- Tests/Fixtures/Generated/Colors/literals-swift4-context-defaults-customname.swift
- Tests/Fixtures/Generated/Colors/literals-swift4-context-defaults-publicAccess.swift
- Tests/Fixtures/Generated/Colors/literals-swift4-context-defaults.swift
- Tests/Fixtures/Generated/Colors/literals-swift4-context-multiple.swift
- Tests/Fixtures/Generated/Colors/swift3-context-defaults-publicAccess.swift
- Tests/Fixtures/Generated/Colors/swift4-context-defaults-publicAccess.swift
- templates/colors/literals-swift3.stencil
- templates/colors/literals-swift4.stencil
- templates/colors/swift3.stencil
- templates/colors/swift4.stencil
_(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
---
Fixes #548.
This PR fixes two issues:
1. The `public` access modifier was not being added correctly when using `publicAccess: true` on the `literals-swift3` and `literals-swift4` templates.
2. Removed superfluous access modifiers from the `swift3` and `swift4` templates (based off of a comment from @djbe here: https://github.com/SwiftGen/SwiftGen/issues/548#issuecomment-427953553).
This includes updates to the stencil template files to correct the issues, and updates to the test data to match the changes.
All tests are currently passing.
> Colors: fix `publicAccess` modifiers

- README.md
_(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
---
I found a typo in `README.md`
- LINE 601: fonts -> strings
- Before
```yaml
fonts:
inputs: /path/to/Localizable.strings
...
```
- After 
```yaml
strings:
inputs: /path/to/Localizable.strings
...
```
> Fix README typo #trivial

- CHANGELOG.md
- Tests/Fixtures/Generated/CoreData/swift3-context-defaults-publicAccess.swift
- Tests/Fixtures/Generated/CoreData/swift3-context-defaults.swift
- Tests/Fixtures/Generated/CoreData/swift4-context-defaults-publicAccess.swift
- Tests/Fixtures/Generated/CoreData/swift4-context-defaults.swift
- Tests/Fixtures/Resources/CoreData/Model.xcdatamodeld/Model 2.xcdatamodel/contents
- Tests/Fixtures/StencilContexts/CoreData/defaults.yaml
- templates/coredata/swift3.stencil
- templates/coredata/swift4.stencil
Closes #565.
Implements the changes discussed in #565, to correctly handle optional scalar attributes in a swifty way.
> Core Data: optional scalar attributes
